FROM node:20-alpine3.17

# Install necessary system libraries
RUN apk add --no-cache libc6-compat netcat-openbsd

WORKDIR /app

# Copy package management files
COPY package*.json ./

# Install dependencies
RUN npm install

CMD ["npm", "run", "dev"] 