services:
  # ------ Flink Job Manager ------ #
  flink-jobmanager:
    build:
      context: ./pyFlink
      dockerfile: Dockerfile
    ports:
      - "7070:8081" # Flink Web UI
    environment:
      - |
        FLINK_PROPERTIES=
          jobmanager.rpc.address: flink-jobmanager
    command: jobmanager

  # ------ Flink Task Manager ------ #
  flink-taskmanager:
    build:
      context: ./pyFlink
      dockerfile: Dockerfile
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
          jobmanager.rpc.address: flink-jobmanager
          taskmanager.numberOfTaskSlots: 8
          taskmanager.memory.process.size: 2048m
          taskmanager.memory.task.off-heap.size: 512m
    command: taskmanager
    depends_on:
      - flink-jobmanager

  # ------ Flink Submission Service ------ #
  flink-submission-service:
    build:
      context: ./flink-submission-service
      dockerfile: Dockerfile
    ports:
      - "7000:8000"
    environment:
      - FLINK_JOBMANAGER=flink-jobmanager:8081
      - FLINK_BIN=flink
      - CHECK_TIMEOUT=30
      - SUBMIT_TIMEOUT=120
    volumes:
      - ./flink-submission-service/app:/app/app
    depends_on:
      - flink-jobmanager
